Document: go-broadcast
Title: Debian go-broadcast Manual
Author: <insert document author here>
Abstract: This manual describes what go-broadcast is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/go-broadcast/go-broadcast.sgml.gz

Format: postscript
Files: /usr/share/doc/go-broadcast/go-broadcast.ps.gz

Format: text
Files: /usr/share/doc/go-broadcast/go-broadcast.text.gz

Format: HTML
Index: /usr/share/doc/go-broadcast/html/index.html
Files: /usr/share/doc/go-broadcast/html/*.html
